classgraph/classgraph

src/main/java/io/github/lukehutch/fastclasspathscanner/FastClasspathScanner.java

When scan root dir for classes. The relative path will be “/”.But the
whitelisted path start without “/“.So, fix it with keeping recursing
for “/“.Please check if it’s suitable.

Fix for issus #10 Whitelisting doesn't work

---

.gitignore
pom.xml
src/test/java/io/github/lukehutch/fastclasspathscanner/FastClasspathScannerTest.java

I'd like to use your project (great work by the way) in Apache Isis, and remove our dependency on Reflections and (from some spiking I've done) reduce our start-up times.
Unfortunately in Apache Isis we are still committed to supporting Java 7, whereas you are building the project for Java 8-only.  
I decided to fork the project to see if it could be backported, and seemingly it can with only a couple of changes to test files.  Other changes in this PR are just some configuration to maven-javadoc-plug (to suppress errors thrown up by docLink) and update ..gitignore to ignore IntelliJ project files.
I expect we'll move Isis up to Java 8 within the next 12 months (certainly not beyond the release of Java 9 in Sept 2016) so perhaps you'd consider supporting Java 7 until then?
ALTERNATIVELY, …

Support Java 7

---

src/main/java/io/github/lukehutch/fastclasspathscanner/classfileparser/ClassInfo.java
src/main/java/io/github/lukehutch/fastclasspathscanner/classfileparser/ClassfileBinaryParser.java
src/main/java/io/github/lukehutch/fastclasspathscanner/classpath/classloaderhandler/JBossClassLoaderHandler.java
src/main/java/io/github/lukehutch/fastclasspathscanner/classpath/classloaderhandler/WeblogicClassLoaderHandler.java
src/main/java/io/github/lukehutch/fastclasspathscanner/scanner/RecursiveScanner.java
src/main/java/io/github/lukehutch/fastclasspathscanner/scanner/ScanSpec.java

This pull request is focused on resolving occurrences of Sonar rule 
squid:S1132 - “Strings literals should be placed on the left side when checking for equality”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1132
Please let me know if you have any questions.
Artyom Melnikov.

Fixing squid:S1132 - Strings literals should be placed on the left side when checking for equality

---

src/main/java/io/github/lukehutch/fastclasspathscanner/classfileparser/ClassInfo.java
src/main/java/io/github/lukehutch/fastclasspathscanner/classpath/ClasspathFinder.java

This pull request is focused on resolving occurrences of some Sonar rules: 
squid:S2221 - “"Exception" should not be caught when not required by called methods”. 
You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S2221
squid:S1210 - ""equals(Object obj)" should be overridden along with the "compareTo(T obj)" method"
You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S1210
Please let me know if you have any questions.
Artyom Melnikov.

Fixing squid:S2221 and squid:S1210 rules

---

pom.xml

Hi Luke,
I would like use your classpath scanner in a OSGi compliant runtime like Apache Felix but that would require some additional metadata to be added to the assembled jar file. Would you be up for merging this PR which adds the required OSGi descriptor to the MANIFEST.MF file? It should not have any impact on any current use of the jar and I have tested the maven build.
Thanks,
Niels

Adding OSGi metadata generation to distribution

---

src/main/java/io/github/lukehutch/fastclasspathscanner/classloaderhandler/FelixClassLoaderHandler.java

If an OSGi bundle does not have a Bundle-Classpath statement then it'll be simply skipped by the FelixClassLoaderHandler. This simple fix adds the bundle itself as a classpath element for scanning.
Can't say if this is a universal solution, but works for me. May be we should always add the bundle, even if it does have a Bundle-Classpath?

add bundle itself as a classpath element if it does not have Bundle-Classpath

---

src/main/java/io/github/lukehutch/fastclasspathscanner/scanner/ClassInfo.java

Exposed `ClassInfo.classpathElementURLs` via a public getter as it's useful for us to know where the class is located.

Added public getter for ClassInfo.classpathElementURLs

---

pom.xml
src/main/java/io/github/lukehutch/fastclasspathscanner/scanner/ClassfileBinaryParser.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue141/Issue141Test.java

I added support for the new module-related constant pool tags to prevent the RuntimeException.
In case that a module-info.class is parsed, I simply return null in readClassInfoFromClassfileHeader (should be ok, as we won't search for module-info classes anyway!?)

~ fix for issue 141

---

src/main/java/io/github/lukehutch/fastclasspathscanner/classloaderhandler/JBossClassLoaderHandler.java

- In 1.6.x the existing FileResourceLoader extends from PathResourceLoader which now uses a java.nio.file.Path as `root` object, previous version this was a `java.io.File`
- It is a simply/fallback fix

JBossClassLoader: upgrade to jboss modules 1.6

---

src/main/java/io/github/lukehutch/fastclasspathscanner/scanner/ScanSpec.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue167/Issue167Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue167/a/TestA.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue167/a/b/TestAB.java

Sort the whitelisted path prefixes to ensure that scannable packages that are also ancestors are correctly evaluated.
Also included a test case to illustrate the issue.

Proposed fix for Issue 167

---

pom.xml
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/TestGetUniqueClasspathElements.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue103/Issue103Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue140/Issue140Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue141/Issue141Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue146/Issue146Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue148/Issue148Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue151/Issue151Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue152/Issue152Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue153/Issue153Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue183/Issue183Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue193/Issue193Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue83/Issue83Test.java
src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue88/Issue88.java
src/test/java/io/github/lukehutch/fastclasspathscanner/test/ClassInfoTest.java
src/test/java/io/github/lukehutch/fastclasspathscanner/test/FastClasspathScannerTest.java

`StrictAssertions` has been replaced by `AssertionsForClassTypes`, but most of the time `Assertions` can be used instead of  `AssertionsForInterfaceTypes` or `AssertionsForClassTypes`.

Update AssertJ to version 3.10.0

---

src/main/java/io/github/classgraph/ClassLoaderHandler.java
src/main/java/io/github/classgraph/classloaderhandler/ClassLoaderHandlerRegistry.java
src/test/java/io/github/classgraph/features/ClassLoaderHandlerSPI.java
src/test/resources/META-INF/services/io.github.classgraph.ClassLoaderHandler

The `ClassLoaderHandler` promises in it's JavaDoc that additional handlers can be loaded through the standard Java SPI. That's not the case.
This PR add this feature and additionally fixes the doc. Please see the single commit message for more detail (quoted below).
All the standard handlers could maybe be loaded through the SPI as well, but to keep the order one would have to add one additional interface method and I understand ClassGraph should still support Java 7, so I didn't add a default interface method.
Also, thanks for your work on ClassGraph, we are using it in [Neo4j-OGM](https://github.com/neo4j/neo4j-ogm) and are currently in the process of upgrading from FastClasspathScanner code.
> This commit adds loading of additional ClassLoaderHandler from Java’s Serviceloader SPI.
> 
> …

Implement loading ClassLoaderHandler from Java’s ServiceLoader.

---

src/main/java/io/github/classgraph/ClassGraphClassLoader.java
src/main/java/io/github/classgraph/classloaderhandler/ClassLoaderHandlerRegistry.java
src/main/java/io/github/classgraph/classloaderhandler/SpringBootRestartClassLoaderHandler.java
src/test/java/io/github/classgraph/issues/issue267/ClassLoadingWorksWithParentLastLoaders.java
src/test/java/io/github/classgraph/issues/issue267/ClassLoadingWorksWithParentLastLoadersStub.java

This commit has to changes:
- It introduces SpringBootRestartClassLoaderHandler and adds it to the registry. RestartClassLoader is parent last and such should be explicitly configured.
- The codewise small but impact wise bigger change is instantiating ClassGraphClassLoader with a call of super(null), eliminating it’s parent.
The later one is done due to the following reason:
ClassGraphClassLoader goes through lengths in `io.github.classgraph.ClassGraphClassLoader#findClass` to determine which class loader has been the source of the scanned class and that works very well.
`findClass` is however called from `loadClass` only if there is no parent class loader or the parent class loader doesn't find the class.
In Spring Boot together with Spring Boots Restart Class Loader we have the …

GH-267: Make ClassGraph work with Spring Boot DevTools / RestartClassLoader.

---

src/main/java/io/github/classgraph/ClassInfo.java
src/test/java/io/github/classgraph/features/DeclaredVsNonDeclared.java

While working on the support for `directOnly()` for annotation lists, I found this subtle, little bug.

Fix retrieval of inherited annotations classes.

---

src/main/java/io/github/classgraph/AnnotationInfoList.java
src/main/java/io/github/classgraph/ClassInfo.java
src/test/java/io/github/classgraph/features/DeclaredVsNonDeclared.java

This allows to filter the list of annotations to direct annotations only. Those are
all annotations directly declared on a element.
The only case directOnly can deliver something else are classes that inherited classes
annotated with meta-annotated @Inherited annotations.
*Note* This PR is rebased onto my branch `fix-retrieval-of-annotation-classes` and should be merged after #271 is merged.
Closes #270 in favor of this PR.

Add directOnly() to public API of AnnotationInfoList.

---

src/main/java/nonapi/io/github/classgraph/classloaderhandler/EquinoxClassLoaderHandler.java

Hey @lukehutch I'm terribly sorry about it, but I've made a mistake on one of the field names that I've added yesterday by accidentally copy pasting an incorrect field name. My mistake doesn't cause any issues with previous versions of equinox class path resolving. 
This pull request aims to fix the issue above. I hope I haven't ruined anything and thank you for responding and releasing my fix yesterday so fast.
Kind Regards,
Zoltán Molnár

Fix field name in EquinoxClassLoaderHandler to nestedDirName

---

.travis.yml

Oracle won't provide "early access" versions as "oraclejdk".  They do offer early access versions by providing "openjdk-ea":
> [...] we don't have an Oracle JDK 12 EA because it's literally the same as our OpenJDK builds, so we likely won't have Oracle JDK ea builds any more now, just GPL ones.
https://twitter.com/DonaldOJDK/status/1032638250899390465
See https://github.com/sormuras/bach/issues/33 for details.

Remove oraclejdk-ea from Travis CI build matrix

---

src/main/java/nonapi/io/github/classgraph/fastzipfilereader/LogicalZipFile.java

Fixes handling of Zip64 archives - start of central directory was not being adjusted to account for the Zip64 end of central directory record and locator.

Recalculate central directory start position for Zip64 archives

---

src/main/java/io/github/classgraph/AnnotationEnumValue.java
src/main/java/io/github/classgraph/ArrayTypeSignature.java
src/main/java/io/github/classgraph/MethodInfo.java
src/main/java/io/github/classgraph/ScanResultObject.java
src/test/java/io/github/classgraph/test/methodinfo/MethodInfoTest.java

Hi Luke,
Added class name to ArrayTypeSignature accordingly to https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html#getName() (actually, it is just parser input)
Tested on Java 11
Regards

Fixed exception during loading of method with array-type arguments

---

src/main/java/nonapi/io/github/classgraph/classloaderhandler/EquinoxClassLoaderHandler.java

If a `NestedBundleFile` contains a `ZipBundleFile` their paths must be concatenated using `!/` instead of `/`.

Fix classpath detection for nested ZipBundleFile

---

src/main/java/io/github/classgraph/Scanner.java
src/main/java/nonapi/io/github/classgraph/classloaderhandler/URLClassLoaderHandler.java
src/test/java/io/github/classgraph/features/CustomURLScheme.java
src/test/java/io/github/classgraph/issues/issue387/Issue387Test.java

This allows scanning of URLs that use a custom scheme.
I've refactored `CustomURLScheme` into a separate class because
`URL.setURLStreamHandlerFactory()` can only be invoked _once_ for a given JVM.

Enable remote jar scanning for URLs inside URLClassLoader.

---

src/main/java/io/github/classgraph/ScanResult.java

adding the cause to the IllegalArgumentException thrown by ScanResult.loadClass() allows to programmatically handle different error cases

Add cause to IllegalArgumentException thrown by ScanResult.loadClass()
