pom.xml
This will remove the junit dependency when used in other projects
=> Include scope modifier for junit dependency

pom.xml
and move release plugins to -Prelease profile such that "mvn clean install" should work everywhere.
=> refactor maven project setup for proper test execution

.travis.yml, README.md
Just in case you want to make sure that your nice project is running on a clean system, you could use the Github associated Travis integration test/build system. Before merging, you would need to go to the travis website and activate your project there.
=> add travis CI config

pom.xml
That's what I do in my own projects.
=> auto-activate release profile when doing release

src/main/java/io/github/lukehutch/fastclasspathscanner/classloaderhandler/WebsphereLibertyClassLoaderHandler.java
I suspect that since removing fallback classloading is removed, the appClassLoader isn't loaded anymore. If that is the case, I now get it from the ThreadContextClassLoader in WAS Liberty.
=> Fixed WASLiberty classloading for version 2.4.0.

src/main/java/io/github/lukehutch/fastclasspathscanner/classloaderhandler/FelixClassLoaderHandler.java
The current FelixClassLoaderHandler doesn't work in OSGI implementations such as Apache Karaf.
This patch provides the following:
- Supports current classloader implementation class name
- Handle content resources properly, rather than assuming that they're all jar files
- Follow bundle wiring where available to pick up classes from linked bundles.
Could potentially be improved further if there was an easy way of comparing package names to the scan spec from within the handler (i.e. we could use this to filter the bundle wiring)
=> Update the FelixClassLoaderHandler

src/main/java/io/github/lukehutch/fastclasspathscanner/classloaderhandler/WeblogicClassLoaderHandler.java
I've tested under my dev. WebLogic server.
The use case (sorry, some package need to be masked out):
`List<Class<?>> objectFactories = new ArrayList<>();
new FastClasspathScanner("XX.YYY").matchClassesWithAnnotation(XmlRegistry.class, objectFactories::add)
.scan();`
The code running in EAR and found all classes with my changes in EAR's classpath.
=> #154 working solution

src/test/java/io/github/lukehutch/fastclasspathscanner/issues/issue175/Issue175Test.java
Since the new version this is a new method I'm having problems with.
=> Another failing test

src/main/java/io/github/classgraph/ClasspathElementDir.java
Fixes https://github.com/classgraph/classgraph/issues/223
=> Assign RAF and channel so they can be closed.

src/main/java/io/github/classgraph/ClasspathElementDir.java, src/main/java/io/github/classgraph/ClasspathElementModule.java, src/main/java/io/github/classgraph/ClasspathElementZip.java, src/main/java/io/github/classgraph/ResourceList.java, src/main/java/io/github/classgraph/utils/AutoCloseableConcurrentQueue.java
=> Close resources in finally block.

src/main/java/io/github/classgraph/MethodInfo.java, src/test/java/io/github/classgraph/issues/issue246/Issue246Test.java
See issue #246 for description.
=> NullPointerException when accessing parameter annotations (#246)

src/test/java/io/github/classgraph/issues/issue267/ClassLoadingWorksWithParentLastLoaders.java, src/test/java/io/github/classgraph/issues/issue267/ClassLoadingWorksWithParentLastLoadersStub.java
This makes the test more future proof and robust.
=> Fix hardcoded name of parent class loader in test.

src/main/java/nonapi/io/github/classgraph/classloaderhandler/EquinoxClassLoaderHandler.java
Hey @lukehutch
The built in class loader handlers work fine in Eclipse up until Photon, but not when you try to use ClassGraph in Eclipse 2018-09 or newer.
This version changes the name of the Java field `cp` to `nestedDirName` in class `NestedDirBundleFile` [see commit](https://github.com/eclipse/rt.equinox.framework/commit/847091d8de7ec31db33fa4d3d7189eb872330eba#diff-846a7057d129eb1904817dd1af240fa7L36) so `EquinoxClassLoaderHandler` is unable to recognize the class path entry properly and appends the output directory as path prefix resulting in ignored class files during scanning.
The pull request aims to fix this issue while maintaining support for older versions.
Kind regards,
Zoltán Molnár
=> Add support for newer versions of equinox for classpath resolving

src/main/java/io/github/classgraph/ClassInfo.java, src/test/java/io/github/classgraph/issues/issue345/Issue345.java
Fixes https://github.com/classgraph/classgraph/issues/345
=> Fixed classfileresource of classes that were created as superclass before they where scanned.

.github/workflows/ci.yml
GitHub Actions:
https://github.com/features/actions
=> add GitHub Actions workflow ci.yml

src/main/java/nonapi/io/github/classgraph/classloaderhandler/TomcatWebappClassLoaderBaseHandler.java
As discussed on Gitter. TomcatWebappClassLoaderBaseHandler should respect org.apache.catalina.loader.WebappClassLoaderBase#delegate to decide whether to use parent-first or parent-last delegation order.
=> Respect Tomcat delegate property for delegation order

.github/workflows/ci.yml
notes: https://github.com/actions/checkout/blob/master/README.md
=> GitHub Actions checkout v2

src/main/java/nonapi/io/github/classgraph/classloaderhandler/QuarkusClassLoaderHandler.java
Since version 1.3 Quarkus changed how classloading works.
This change adds support for the new Quarkus classloader
and removes unecessary entries added for 1.2 Runtimeclassloader.
=> Added support for Quarkus 1.3

pom.xml
Closes [408](https://github.com/classgraph/classgraph/issues/408)
=> 408: Added optional resolution to jdk and sun packages

src/main/java/nonapi/io/github/classgraph/classloaderhandler/WebsphereLibertyClassLoaderHandler.java
Fix for LIberty issue #414
In this fix, I attempt to use the methods that just return the classpath urls.   I can't regression test against any old Liberties so I have it fallback to the old logic whenever the new logic fails.
- Use SmartClassPath's "getClassPath" to get the classpath URL(s).
- If that doesn't work for some reason, revert to processing individual SmartClassPath elements.
- Attempt to use "getContainerURLs" on SmartClassPath's elements
- If that doesn't work, revert to introspection on the "container"
- Attempt to use "getURls" on the container.
- If that doesn't work,  revert to introspection on the "delegate".
=> Fix for Libery running in "overlay"
